export const GET_PRODUCTS = 'GET_PRODUCTS';
export const LIST_LOADING = 'LIST_LOADING';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_LIST_LOADING = 'SEARCH_LIST_LOADING';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const NEXT_INSTRUCTION = 'NEXT_INSTRUCTION';